In [1]:
#creating numpy/ n-d array
import numpy as np

In [2]:
array1=np.array([1,2,3,4,5,6,8])

In [3]:
array1

array([1, 2, 3, 4, 5, 6, 8])

In [4]:
array2=np.array([[2,3,4],[5,6,7]])

In [5]:
array2

array([[2, 3, 4],
       [5, 6, 7]])

In [6]:
array3=np.zeros((2))

In [7]:
array3

array([0., 0.])

In [8]:
array4=np.zeros((2,3))

In [9]:
array4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
array5=np.zeros((2,3,4))

In [11]:
array5

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
#Creating an N-D Array with np.zeros, np.ones, and np.full

In [13]:
#Using np.zeros

In [14]:
import numpy as np

# Creating a 3-D array filled with zeros
array_zeros = np.zeros((2, 3, 4))  # shape: 2x3x4
print(array_zeros)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [15]:
#Using np.ones

In [16]:
import numpy as np

# Creating a 3-D array filled with ones
array_ones = np.ones((2, 3, 4))  # shape: 2x3x4
print( array_ones)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [17]:
#Using np.full

In [18]:
import numpy as np

# Creating a 3-D array filled with a specified value
array_full = np.full((2, 3, 4), 7)  # shape: 2x3x4, filled with 7
print( array_full)


[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]


In [19]:
#Creating an N-D Array with np.arange and np.reshape

In [20]:
import numpy as np

# Creating a 1-D array and reshaping it to a 3-D array
array_reshaped = np.arange(24).reshape((2, 3, 4))  # shape: 2x3x4
print("3-D array created with np.arange and reshaped:\n", array_reshaped)


3-D array created with np.arange and reshaped:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [21]:
import numpy as np

# Creating a 1-D array of evenly spaced values and reshaping it to a 2-D array
array_linspace = np.linspace(0, 24, 23)  # 24 values, reshaped to 4x6
print("2-D array created with np.linspace and reshaped:\n", array_linspace)


2-D array created with np.linspace and reshaped:
 [ 0.          1.09090909  2.18181818  3.27272727  4.36363636  5.45454545
  6.54545455  7.63636364  8.72727273  9.81818182 10.90909091 12.
 13.09090909 14.18181818 15.27272727 16.36363636 17.45454545 18.54545455
 19.63636364 20.72727273 21.81818182 22.90909091 24.        ]


In [22]:
import numpy as np

# Creating a 1-D array of evenly spaced values and reshaping it to a 2-D array
array_linspace = np.linspace(0, 23, 24).reshape((4, 6))  # 24 values, reshaped to 4x6
print("2-D array created with np.linspace and reshaped:\n", array_linspace)


2-D array created with np.linspace and reshaped:
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [23]:
#Key Attributes of NumPy Arrays

In [24]:
#ndim

In [25]:
import numpy as np

# Create a 3-D array
array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
array.ndim


3

In [26]:
#shape

In [27]:
import numpy as np

# Create a 3-D array
array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
array
array.shape


(2, 2, 3)

In [28]:
 #size

In [29]:
import numpy as np

# Create a 3-D array
array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
array.size


12

In [30]:
#dtype

In [31]:
import numpy as np

# Create a 3-D array
array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array.dtype)


int32


In [32]:
#itemsize

In [33]:
import numpy as np

# Create a 3-D array
array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array.itemsize)


4


In [34]:
import numpy as np

# Create arrays
arr1 = np.array([[1, 2, 3, 4], [4,5,6,7]])
arr2 = np.array([[5, 6, 7, 8], [9,2,3,4]])

# Element-wise addition
addition = arr1 + arr2
print("Addition:", addition)

# Element-wise multiplication
multiplication = arr1 * arr2
print("Multiplication:", multiplication)

# Element-wise exponentiation
exponentiation = arr1 ** 2
print("Exponentiation:", exponentiation)

Addition: [[ 6  8 10 12]
 [13  7  9 11]]
Multiplication: [[ 5 12 21 32]
 [36 10 18 28]]
Exponentiation: [[ 1  4  9 16]
 [16 25 36 49]]


In [1]:
#creating NumPy arrays with random numbers

In [2]:
#numpy.random.rand: Generates random numbers between 0 and 1.


import numpy as np

# Create a 1D array with 10 random numbers between 0 and 1
array_1d = np.random.rand(10)
print(array_1d)

[0.07062492 0.14154504 0.83116543 0.41889785 0.19763788 0.64313438
 0.85457248 0.23369787 0.42285532 0.72758517]


In [3]:
# Create a 2D array with random numbers between 0 and 1
array_2d = np.random.rand(3, 4)
print(array_2d)

[[0.2240083  0.33125225 0.62155789 0.85528286]
 [0.96562062 0.00835148 0.77283353 0.49779664]
 [0.34319465 0.50050927 0.86125554 0.86067338]]


In [4]:
#numpy.random.randn: Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).


import numpy as np

# Create a 1D array with 10 random numbers from a standard normal distribution
array_1d_normal = np.random.randn(10)
print(array_1d_normal)

# Create a 2D array with random numbers from a standard normal distribution
array_2d_normal = np.random.randn(3, 4)
print(array_2d_normal)

[-0.69363032  0.02574073  0.16594774  0.42396946 -0.32485488  1.46932913
 -0.68870583 -1.00810267  0.33785543 -0.09651295]
[[-0.09945682  0.82200449 -0.47309611 -0.48793498]
 [ 0.52393746  0.32153731  0.88466645 -0.10065787]
 [-1.32610198 -0.68308517 -0.07328512  0.21971345]]


In [5]:
#numpy.random.randint: Generates random integers between a specified range.


import numpy as np

# Create a 1D array with 10 random integers between 1 and 100
array_int_1d = np.random.randint(1, 100, size=10)
print(array_int_1d)

# Create a 2D array with random integers between 1 and 100
array_int_2d = np.random.randint(1, 100, size=(3, 4))
print(array_int_2d)

[83 56 74 44 14  6 46 74 89 89]
[[23 38 83 79]
 [94 83 91 28]
 [33 10 82 42]]


In [6]:
#numpy.random.random_sample: Generates random floats between 0 and 1.

import numpy as np

# Create a 1D array with 10 random floats between 0 and 1
array_1d_sample = np.random.random_sample(10)
print(array_1d_sample)

# Create a 2D array with random floats between 0 and 1
array_2d_sample = np.random.random_sample((3, 4))
print(array_2d_sample)

[0.35044876 0.76395626 0.96433003 0.27564087 0.89549836 0.92722882
 0.32021201 0.67301004 0.7436585  0.90763191]
[[0.31469479 0.77424873 0.84336016 0.57397322]
 [0.79746599 0.25137003 0.65103988 0.47356098]
 [0.90545014 0.66607127 0.60154642 0.77919685]]


In [7]:
#numpy.random.choice: Generates a random sample from a given 1-D array.


import numpy as np

# Create a 1D array with a random sample of 10 elements from the given array
array_choice_1d = np.random.choice([1, 2, 3, 4, 5], size=10)
print(array_choice_1d)

# Create a 2D array with a random sample from the given array
array_choice_2d = np.random.choice([1, 2, 3, 4, 5], size=(3, 4))
print(array_choice_2d)

[1 2 5 3 1 3 2 1 3 4]
[[2 2 1 4]
 [2 3 2 1]
 [2 5 5 4]]


In [8]:
#numpy.random.uniform: Generates random floats in a specified range.


import numpy as np

# Create a 1D array with 10 random floats between 10 and 20
array_uniform_1d = np.random.uniform(10, 20, size=10)
print(array_uniform_1d)

# Create a 2D array with random floats between 10 and 20
array_uniform_2d = np.random.uniform(10, 20, size=(3, 4))
print(array_uniform_2d)

[11.37022745 17.98900259 14.02390088 10.3975039  12.13907053 12.68152876
 17.60089743 17.9301565  12.73905032 15.08072101]
[[19.18817223 18.21143099 17.5580599  18.17819691]
 [11.85746711 16.533831   16.3754192  14.23872102]
 [14.17363022 16.21748527 16.2649934  14.93467844]]


In [9]:
#Searching Functions in NumPy
#np.where(condition)

#Returns the indices where the specified condition is true in the array.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
indices = np.where(arr > 2)
print(indices)  # Output: (array([2, 3, 4]),)

(array([2, 3, 4], dtype=int64),)


In [15]:
#np.argmax(array) and np.argmin(array)
#Returns the indices of the maximum and minimum values in the array, respectively.

import numpy as np

arr = np.array([1, 5, 3, 7, 2])
max_index = np.argmax(arr)
min_index = np.argmin(arr)
print(max_index, min_index)  # Output: 3 0

#Sorting Functions in NumPy
#np.sort(array)

#Returns a sorted copy of the array.
import numpy as np

arr = np.array([3, 1, 5, 2, 4])
sorted_arr = np.sort(arr)
print(sorted_arr)  # Output: [1 2 3 4 5]

3 0
[1 2 3 4 5]


In [14]:
#np.argsort(array)

#Returns the indices that would sort the array.

import numpy as np

arr = np.array([3, 1, 5, 2, 4])
sorted_indices = np.argsort(arr)
print(sorted_indices)  # Output: [1 3 0 4 2]

[1 3 0 4 2]


In [13]:
#np.searchsorted(array, values)
#This function is used to find the indices where elements from values should be inserted to maintain order in array. It assumes array is sorted.

import numpy as np

arr = np.array([1, 3, 5, 7, 9])
values = [2, 8]
indices = np.searchsorted(arr, values)
print(indices)  # Output: [1 4]


[1 4]


In [12]:
#Filtering in NumPy
#Boolean Indexing

#Using boolean arrays to filter elements in an array based on a condition.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
condition = arr > 2
filtered_arr = arr[condition]
print(filtered_arr)  # Output: [3 4 5]
np.where(condition)

#As mentioned earlier, np.where can be used to filter elements based on a condition and return indices.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
indices = np.where(arr > 2)
filtered_arr = arr[indices]
print(filtered_arr)  # Output: [3 4 5]

[3 4 5]
[3 4 5]


In [17]:
'''1. np.insert(array, index, values, axis=None)
Purpose: Inserts values along the given axis before the given index.

Parameters:

array: Input array.
index: Index or indices before which values is inserted.
values: Values to be inserted.
axis: Axis along which to insert. If not specified, the input array is flattened.
Returns: A new array with values inserted before index.
'''
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Inserting a single value at index 2
new_arr = np.insert(arr, 2, 10)
print(new_arr)  # Output: [ 1  2 10  3  4  5]

# Inserting multiple values at index 1
new_arr = np.insert(arr, 1, [6, 7])
print(new_arr)  # Output: [1 6 7 2 3 4 5]


'''2. np.delete(array, index, axis=None)
Purpose: Deletes elements along the given axis before the given index.

Parameters:

array: Input array.
index: Index or indices to delete.
axis: Axis along which to delete. If not specified, the input array is flattened.
Returns: A new array with elements at index deleted.
'''

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Deleting element at index 2
new_arr = np.delete(arr, 2)
print(new_arr)  # Output: [1 2 4 5]

# Deleting elements at indices 0 and 3
new_arr = np.delete(arr, [0, 3])
print(new_arr)  # Output: [2 3 5]

[ 1  2 10  3  4  5]
[1 6 7 2 3 4 5]
[1 2 4 5]
[2 3 5]
